name: 'Rust CI'

on:
  push:
    branches: [ solution ]
  pull_request:
    branches: [ solution ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_n_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Check code format
      run: cd rust && rustfmt --edition 2018 -l --check src/*.rs
    - name: Build
      run: cd rust && cargo build --verbose
    - name: Run tests
      run: cd rust && cargo test --verbose
